## Calibration = Rotation + Translation

In [92]:
import numpy as np
import matplotlib.pyplot as plt

In [93]:
with open("../data/KITTI/training/calib/000000.txt") as f:
    lines = f.readlines()
lines

['P0: 7.070493000000e+02 0.000000000000e+00 6.040814000000e+02 0.000000000000e+00 0.000000000000e+00 7.070493000000e+02 1.805066000000e+02 0.000000000000e+00 0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 0.000000000000e+00\n',
 'P1: 7.070493000000e+02 0.000000000000e+00 6.040814000000e+02 -3.797842000000e+02 0.000000000000e+00 7.070493000000e+02 1.805066000000e+02 0.000000000000e+00 0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 0.000000000000e+00\n',
 'P2: 7.070493000000e+02 0.000000000000e+00 6.040814000000e+02 4.575831000000e+01 0.000000000000e+00 7.070493000000e+02 1.805066000000e+02 -3.454157000000e-01 0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 4.981016000000e-03\n',
 'P3: 7.070493000000e+02 0.000000000000e+00 6.040814000000e+02 -3.341081000000e+02 0.000000000000e+00 7.070493000000e+02 1.805066000000e+02 2.330660000000e+00 0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 3.201153000000e-03\n',
 'R0_rect: 9.999128000000e-01 1.009263000000e

In [94]:
line = []
for i in range(0, len(lines)-1):
    line.append(lines[i])

p0 = line[0].strip().split()[1:]
p1 = line[1].strip().split()[1:]
p2 = line[2].strip().split()[1:]
p3 = line[3].strip().split()[1:]
r0_rect = line[4].strip().split()[1:]
tr_velo_to_cam = line[5].strip().split()[1:]
tr_imu_to_velo = line[6].strip().split()[1:]

In [95]:
# Homogenous matrix (R|t)

tr_velo_to_cam = np.array(tr_velo_to_cam, dtype=np.float32).reshape(3, 4)
print(tr_velo_to_cam)

[[ 0.00692796 -0.9999722  -0.00275783 -0.02457729]
 [-0.00116298  0.00274984 -0.9999955  -0.06127237]
 [ 0.9999753   0.00693114 -0.0011439  -0.3321029 ]]


In [96]:
# Second transformation is to go to Rectified camera frame
r0_rect = np.array(r0_rect, dtype=np.float32).reshape(3, 3)
print(r0_rect)

[[ 0.9999128   0.01009263 -0.00851193]
 [-0.01012729  0.9999406  -0.00403767]
 [ 0.00847067  0.00412352  0.9999556 ]]


In [97]:
# image pixel matrix for 2d image projection
p2 = np.array(p2, dtype=np.float32).reshape(3, 4)
print(p2)

[[ 7.070493e+02  0.000000e+00  6.040814e+02  4.575831e+01]
 [ 0.000000e+00  7.070493e+02  1.805066e+02 -3.454157e-01]
 [ 0.000000e+00  0.000000e+00  1.000000e+00  4.981016e-03]]


In [98]:
print("P2:\n", p2)
print("\nR0_rect:\n", r0_rect)
print("\nT_velo_cam:\n", tr_velo_to_cam)

P2:
 [[ 7.070493e+02  0.000000e+00  6.040814e+02  4.575831e+01]
 [ 0.000000e+00  7.070493e+02  1.805066e+02 -3.454157e-01]
 [ 0.000000e+00  0.000000e+00  1.000000e+00  4.981016e-03]]

R0_rect:
 [[ 0.9999128   0.01009263 -0.00851193]
 [-0.01012729  0.9999406  -0.00403767]
 [ 0.00847067  0.00412352  0.9999556 ]]

T_velo_cam:
 [[ 0.00692796 -0.9999722  -0.00275783 -0.02457729]
 [-0.00116298  0.00274984 -0.9999955  -0.06127237]
 [ 0.9999753   0.00693114 -0.0011439  -0.3321029 ]]
